- hosts: pulsar-servers
  tasks:
    - name: Overwrite dependency_resolvers.conf
      copy:
        src: files/pulsar/dependency_resolvers_conf.xml
        dest: /opt/pulsar/config/dependency_resolvers_conf.xml
    - name: Overwrite local_env.sh
      copy:
        src: files/pulsar/local_env.sh
        dest: /opt/pulsar/config/local_env.sh
    - name: Overwrite app.yml
      copy:
        src: files/pulsar/app.yml
        dest: /opt/pulsar/config/app.yml
    # - name: Checkout Galaxy as dependency for pulsar
    #   git:
    #     repo: 'https://github.com/galaxyproject/galaxy.git'
    #     dest: /opt/pulsar/dependencies/galaxy
    #     force: yes
    # - name: Install all the requirements for Galaxy
    #   script: files/pulsar/galaxy_dependencies.sh
    #   become: yes
    - name: Update pulsar to newest version
      script: files/pulsar/update_pulsar.sh
    - name: SystemD daemon-reload and enable/start service
      systemd:
        state: restarted
        enabled: yes
        name: pulsar.service
        daemon_reload: yes
      become: yes
